/*
 * Course: CS215-009
 * Project: Lab 9 (first part of Project 2)
 * Purpose: this program repeatedly allows the user to practice FOUR basic math operations
 *         until the user chooses to quit the program
 *         it generates num1 as the first operand: a one digit, or two digits, or three digits number
 *         it then generates a single digit integer num2 as the second operand: at the range of [2,9]
 *         to practice FOUR basic math operations: + - * and ÷
 *         Note there are two requirements for the questions due to the users are fourth-grade elementtary school students:
 *         (1) For substraction questions, the answers cannot be negative numbers;
 *         (2) For division questions, the answers can only be whole number without reminder.
 *         it then asks the user to enter the answer to four questions:
 *         (1)num1 + num2;
 *         (2)num1 - num2;
 *         (3)num1 * num2;
 *         (4)num1 ÷ num2;
 *         if the answer is correct, a message of congratulations should be printed;
 *         if the answer is not correct, a sorry message should be printed, then followed by the correct answer.
 *Author: (your name)
 */

#include <iostream>
#include <cstdlib>
#include <ctime>
#include <string>
#include "MathOperations.h"

using namespace std;

// declare global variable (constant only, avoid using global variable!)
const int LEN = 2;  // represents the length of a array: to store one character and one terminator

int main()
{
    // define some constants to set up the required range
    const int ANSWERMIN = 2;   // Minimum value of the possible quotient for division problem
    const int ANSWERMAX = 99;  // Maximum value of the possible quotient for division problem
    const int OP2MIN = 2;       // Minimum value of the second operand
    const int OP2MAX = 9;       // Maximum value of the second operand

    int num1;          // The first operand for the operations
    int num2;          // The second operand for the operations
    string choice;     // The user's choice: either answer the question or quit

    // Seed the random number generator.
    srand(time(NULL));

    cout << "Do you want to practice four basic math operations?" << endl;
    cout << "Press Enter to continue or press Q(or q) to quit...";
    getline(cin, choice);

    while (choice != "Q" && choice != "q")
    {
        MathOperations question;

        // while generating the questions to solve, it needs to satisfy two requirements:
        // (1) For subtraction questions, the answer cannot be negative number;
        // (2) For division questions, the answer can only be whole number
        // In order to satisfy the above two requirement, num1 is generated by num2 * RS (RS is in the range of [2, 99])

        // Generate a number at the range of [ANSWERMIN, ANSWERMAX]
        int RS = ANSWERMIN + rand() % (ANSWERMAX - ANSWERMIN + 1);
        // Generate a single digit number at the range of [2,9] as the second operand
        num2 = OP2MIN + rand() % (OP2MAX - OP2MIN + 1);
        // Generate first operand either a one-digit, two-digit or three-digit number
        num1 = RS * num2;

        // With the same operands: num1 and num2
        // (1)Produce an addition question; print the question;  then collect the user input answer
        // (2)Produce a substraction question; print the question;  then collect the user input answer
        // (3)Produce a multiplication question; print the question;  then collect the user input answer
        // (4)Produce a division question; print the question;  then collect the user input answer
        question.setOperands(num1, num2);

        question.Addition();
        int studentAnswer = question.collectUserAnswer();
        if (question.checkAnswer(studentAnswer))
            cout << "Congratulations! " << studentAnswer << " is the right answer." << endl;
        else
            cout << "Sorry, the correct answer is " << question.getAnswer() << "." << endl;

        question.Subtraction();
        studentAnswer = question.collectUserAnswer();
        if (question.checkAnswer(studentAnswer))
            cout << "Congratulations! " << studentAnswer << " is the right answer." << endl;
        else
            cout << "Sorry, the correct answer is " << question.getAnswer() << "." << endl;


        question.Multiplication();
        studentAnswer = question.collectUserAnswer();
        if (question.checkAnswer(studentAnswer))
            cout << "Congratulations! " << studentAnswer << " is the right answer." << endl;
        else
            cout << "Sorry, the correct answer is " << question.getAnswer() << "." << endl;

        question.Division();
        studentAnswer = question.collectUserAnswer();
        if (question.checkAnswer(studentAnswer))
            cout << "Congratulations! " << studentAnswer << " is the right answer." << endl;
        else
            cout << "Sorry, the correct answer is " << question.getAnswer() << "." << endl;

        cout << "Do you want to practice four basic math operations?" << endl;
        cout << "Press Enter to continue or press Q(or q) to quit...";
        getline(cin, choice);
    }

    cout << "Thank you for practicing Basic Math Operations." << endl;
    return 0;
}